### ISSUE TITLE
no migration files found in this project. forgot to commit? 

### ISSUE THREAD

**Issue by sg552** [Dania02525/elixir_trading_platform#1]
Hi ,  I got error when running "mix ecto.migrate", the message is: 

```
** (Mix) Could not find migrations directory "/workspace/elixir_trading_platform/priv/repo/migrations"
for repo ElixirExchange.Repo.
```

I checked the priv/repo/migrations folder,  yes, it's not found.

Please take a look, thanks!

**Comment by Dania02525** [comment]
Hey there, wow this is an old issue.  there are no database tables in this project at the moment, hence no migrations

**Comment by sg552** [comment]
..... OK, anyway, thanks for your answer after 4 years waiting. I used Ruby instead of Pheonix.
